### ISSUE TITLE
collectionObservable does not increment length or notify subscribers

### ISSUE THREAD

**Issue by Skaryon** [kmalakoff/knockback#157]
On 1.1.0 if I .push a new item to a collectionObservable, the underlying collection is properly updated but the length of the collectionObservable it not incremented and no subscribers are notified (so the UI is not updated).
If I just switch back to 1.0.0 it works fine.

**Comment by kmalakoff** [comment]
I'm sorry about this. 

Can you confirm that things work as expected if the major change from 1.1.0 is removed?

https://github.com/kmalakoff/knockback/blob/master/knockback.js#L2284

change
```
	      return (retainExisting ? this.retain(observable, obj, creator) : observable);
```

to
```
	      return observable;
```

**Comment by Skaryon** [comment]
That fixes the problem indeed, Thanks for your reply!

Another thing: From reading the documentation, I was under the impression that you could pass a ViewModel constructor as the second argument that stuff you push into the collectionObservable would be converted into, but it doesn't seem to work that way. Am I understanding it wrong?

BTW: My company is building a service where people can create and monitize web bassed magazines in an intuitive editor, based on knockback:
www.wondermags.com

**Comment by kmalakoff** [comment]
Awesome to see knockback out in the world! thanks for sharing...

Thank you for checking that line. Hmmmm. That means https://github.com/kmalakoff/knockback/issues/155 breaks some functionality that we don't yet have test coverage for. 

To track this down...can you explain a bit more about what a minimal broken test case may look like so @piusatst and I can think about what might be happening? (if you can share production code, that is better, but I know that's not often possible)

For ViewModel constructors in CollectionObservables, there are a few patterns / signatures to give some flexibility. Check out the variations in the tests [here](https://github.com/kmalakoff/knockback/blob/master/test/spec/core/view-model.tests.coffee#L291).

**Comment by Skaryon** [comment]
Hey,

sorry for the late response. 

I created a test to actually test a sortable binding we were using:

```javascript
kb.ViewModel.extend({
        i: 1,
        constructor: function (model, options)
        {
            options          = options || {};
            options.excludes = ['lines'];
            this.lines = new kb.CollectionObservable(model.get('lines'), kb.ViewModel);
            kb.ViewModel.apply(this, [model, options]);
            return this;
        },

        addItem: function ()
        {
            var obj = {name: "test" + (this.i++)};
            var line = new SortItemModel(obj);
            this.lines.push(new kb.ViewModel(line));
            console.log("CollectionObservable length:", this.lines.length);
            console.log("Collection length:", this.lines.collection().length);
        }
    });
```

With this template:
```html
<button data-bind="click: addItem.bind($data)">add line</button>
<br><br>

This collection is sortable: <br>
<ul data-bind="sortable: lines">
    <li>
        <span data-bind="html: name"></span>
    </li>
</ul>

This is a clone which should stay the same: <br>
<ul data-bind="foreach: lines">
    <li>
        <span data-bind="html: name"></span>
    </li>
</ul>
```


Now in 1.0.0 I can happily push the addItem button and it add item. Sorting also works fine. In 1.1.0 the view is never updated and no subscription on the observable are triggered. I hope I'm not using this wrong.

One thing I just noticed is that in both 1.0.0 and 1.1.0 the console output from addItem is as such:

CollectionObservable length: 0
Collection length: 1
CollectionObservable length: 0
Collection length: 2
...

Shouldn't both lengths be imcremented?

**Comment by kmalakoff** [comment]
Thank you for the examples and investigations. I'll dig into this over the weekend!

**Comment by kmalakoff** [comment]
@Skaryon I've taken a look and it looks like there is a dereference missing in the console logging.

This:
```
            console.log("CollectionObservable length:", this.lines.length);
```

should be:
```
            console.log("CollectionObservable length:", this.lines().length);
```

Since you are trying to find the length of the View Models array stored inside of the Collection Observable `lines`.

**Comment by kmalakoff** [comment]
Also, one things I noticed is that typically, I would modify the model layer directly and just have the view layer reflect it. Here's how I would simplify the example:

```
var SortItemModel = Backbone.Model.extend({});

var ViewModel = kb.ViewModel.extend({
  i: 1,
  addItem: function ()
  {
    var obj = {name: "test" + (this.i++)};
    var line = new SortItemModel(obj);
    this.model().get('lines').push(line);
    console.log("CollectionObservable length:", this.lines().length);
    console.log("Collection length:", this.model().get('lines').length);
  }
});
```

Here is a copy on develop: https://github.com/kmalakoff/knockback/commit/a2ff99e1516a3fea36e264aad42c6def6a57f423

**Comment by piusatst** [comment]
Hi kmalakoff,

I've only just noticed the issue now. Sorry, for not replying!

What is the status of this issue? I can see its closed, but I don't see a resolution here.

I have also noticed the same problem, but wasn't sure if it was my setup or the framework.

I put in a manual fix myself by adding a `collection.trigger('sort')` to forced the collectionObservable being notified. I have been busy getting a new feature out the door to make a proper report or investigation.

Stepping through the code, I have traced the problem down to line 368 of `collection-observable.coffee`:
```
367:  _onObservableArrayChange: (models_or_view_models) -> return kb.ignore =>
368:       return if @in_edit # we are doing the editing
```

I can see that the `@in_edit` flag gets set to prevent the collection-observable notifying too many times, but i also prevents the notification of the collection change when it should happen.

My suggestion is to fire a notification after a `@in_edit--`, but i'm not sure where is the best place to do that, since i'm not entirely familiar with the `@in_edit` flow yet.

Do you have any idea why the 1.1.0 change would have caused the in_edit flag to be true when this function is fired?

**Comment by kmalakoff** [comment]
Hi @piusatst,

Thank you for investigating further...I'm sorry for the impact on your release. 

I closed it because the test case passed when I corrected it to `this.lines().length`. I guess it is not closed! 

@in_edit` is used to differentiate between an externally triggered change and a change that is triggered within the collection observable code that is currently being processed since knockback supports two-way sync (eg. changing the models in the collection OR changing the view models in the collection observable). 
 
One reason for `@in_edit` to be true when the function is fired is that the triggering is happening within an existing update. Another reason could be that there is a situation where `@in_edit` book keeping is asymmetric. 

`@in_edit` might be a red herring if you are calling `collection.trigger('sort')` within an update cycle. Deferring the manual refresh should not encounter the problem unless it is the asymmetric case. Can you clarify if you are manually triggering it within an update cycle?

If we go back to your submitted test case (https://github.com/kmalakoff/knockback/commit/a2ff99e1516a3fea36e264aad42c6def6a57f423), did I incorrectly understand it? Would you be able to help me with a broken case that I can debug?

**Comment by piusatst** [comment]
I'm calling `collection.trigger('sort')` after the update cycle is finished. I added that as a fix because the `CollectionObservable` no longer gets notified of an update to the collection.

I think @Skaryon is reporting the same issue I have seen and his test case may have been a error, but I can't be sure. 

Let's wait for him to respond. If there is still an issue for him, I'll help find out why the CollectionObservable no longer gets notified on a push. 

If it is a problem with the way he is referencing the length of the CollectionObservable, and your response has fixed his issue, I think we don't need to worry about it.

**Comment by kmalakoff** [comment]
@Skaryon given the problems, I've published a new version of Knockback with the deep reference counting default off and configurable as follows:

```
kb.configure({deep_retain: true})
```

@piusatst you should use the deep_retain option to keep your optimizations in https://github.com/kmalakoff/knockback/issues/155
