### ISSUE TITLE
Replacing model breaks the data-bindings

### ISSUE THREAD

**Issue by Amsvartner** [kmalakoff/knockback#166]
Hi. I am trying to replace the **model** in a **viewModel** by using it's `write` method, like so:
```
var vm = kb.viewModel(model1);
vm.model(model2);
``` 

I suspect that I am going about this the wrong way as it's stops working entirely once I've switched to and fro a couple of times. I'll include a simple fiddle below to demonstrate the issue.

https://jsfiddle.net/o3kpz86t/3/

Somehow `__kb["object"]` ends up referring to the previous **model** after the second switch, and so the `kb.viewModel.write()` method stops at the `kb.utils.wrappedObject(_this) === new_model` check and returns without updating the **viewModel** at all. After that, it's constantly bugged out. Also, instead of actually replacing the **model**, it adds one **viewModel** per model to the store, is that intentional? All of these **viewModels** seems to have identical internal `cid` attributes, which may or may not be affecting the store not keeping everything in sync. I don't understand enough about the inner workings of Knockback to pinpoint the underlying problem.

Is there any other way that I can replace the **model** of a **viewModel**, that properly updates the internal store and does not create new **viewModels**?

**Comment by kmalakoff** [comment]
I've looked at your jsFiddle and it looks like you are doing this correctly. 

Also, I appreciate you stepping through the code to try to troubleshoot this. If the model has changed, it should not add a new view model to the cache and if the wrappedObject it updated, it should be changed in place. I suspect that if the cid doesn't change is probably due to a check not updating the observables rather than being a contributor to the problem.

Typically, what I would do is add a test for multiple model updates and then troubleshoot the code paths. I haven't been actively supporting this library since moving to React myself. How important is this to you?

**Comment by Amsvartner** [comment]
Yeah, I've put a good week into researching this, but it's just beyond my skill set to solve it, I think.

I'm using Knockback for a web application that controls the production of concrete, which began development in 2011 and is now being used at some 50 concrete plants. I'm looking into migrating to React, but it's going to have to be a progressive thing as I'm the only front end developer and there's several hundreds of thousands lines of code. It's going to be a while until we can stop relying on Knockback, so I would truly appreciate any help with this.

**Comment by kmalakoff** [comment]
Sorry that you weren't able to crack it. I know things are a little complicated. I really appreciate that you tried.

Yesterday, I started to look into this. I upgrading things last in 2017 so I'm running into some challenges getting all the scripts running to start the process of fixing this. I will help you with this and will devote some time to upgrading and investigating over the coming couple of days. I'll keep you posted!

**Comment by kmalakoff** [comment]
I was able to get the build scripts working and troubleshot the bug. It looks like the line you mentioned `kb.utils.wrappedObject(_this) === new_model` seems to have been a mistake since the model wasn't being updated on the view model itself. It should be fixed now and published on npm (https://www.npmjs.com/package/knockback - knockback@1.2.3).

Let me know if it doesn't work for any reason.
